### ISSUE TITLE
Is this package maintained?

### ISSUE THREAD

**Issue by Kyon147** [EastsideCo/polaris-vue#17]
Been trying out the package for a project and noticed some bugs, looking at the PRs they have been sitting there for some time.

If this is not maintained I will fork from it.

**Comment by EMachado88** [comment]
It's lacking some stuff.
I don't think it's maintained anymore.

If you do fork, please advise me. I have a package that depends on it and would like to keep up with the Vue port.

**Comment by Kyon147** [comment]
@EMachado88 - decided to fork it this evening, plan to make some minor bug fixes that I have noticed and will push them later in the week

https://github.com/Kyon147/polaris-vue
